/*
This File was autogenerated by sqlBuilder
*/

'use strict';

class limit extends SQLBuilder.SQLHelper {
	constructor(sql){
		super(sql);

		this.preBuildHookString = function (query, idententifier) {
			// pg is the only rdbms which knowns
			// the keyword ALL for LIMIT
			if (this.isPostgreSQL()) return query;

			if (query === 'ALL') {
				if (this.isMySQL() || this.isMariaDB()) {
					query = Number.MAX_SAFE_INTEGER; //from the mysqldoc's 18446744073709552000
				} else if (this.isSQLite()) {
					query = -1;
				}
			}
			return query;
		});

		this.Types({
			Number: { syntax: this.Syntax('<value-param>') },
			String: {
				syntax: {
					ALL: this.Syntax('<value>', this.preBuildHookString)
				}
			}
		});
	}
}

module.exports = {
	definition: limit
}
